[project]
name = "jupychatplot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "hongyu", email = "hongyu@aestheticintegration.com" }
]
requires-python = ">=3.13"
dependencies = [
    "langgraph>=0.2.60",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
